openapi: 3.1.0
info:
  title: Mouse Cursor INF Generator
  description: API for generating .inf files for custom mouse cursors.
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Main (production) server

paths:
  /generateInf:
    post:
      summary: Generate INF file
      description: Generates an INF file for custom mouse cursors.
      operationId: generateInfFile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                schemeName:
                  type: string
                  description: The name of the cursor scheme.
                  example: "MyCustomScheme"
                cursorFiles:
                  type: object
                  description: A dictionary of cursor file names and their corresponding file paths.
                  additionalProperties:
                    type: string
                  example:
                    "arrow.cur": "C:\\Cursors\\arrow.cur"
                    "hand.cur": "C:\\Cursors\\hand.cur"
      responses:
        '200':
          description: INF file generated successfully.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
